name: Build ATLAS xcache image

on:
  push:
    branches:
      - "testing-upgrade"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Docker Build & Push XCACHE image
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: ivukotic/atlas-xcache
          tags: testing, ${{ github.sha }}
          directory: "atlas-xcache"
          dockerfile: "atlas-xcache/Dockerfile"
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build & Push HEARTBEATS image
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: ivukotic/atlas-xcache-heartbeats
          tags: testing, ${{ github.sha }}
          directory: "atlas-xcache"
          dockerfile: "atlas-xcache/Dockerfile.heartbeats"
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Show XRDCP version
        run: |
          docker run --rm ivukotic/atlas-xcache:testing xrdcp -version

      - name: Show Rucio client version
        run: |
          docker run --rm ivukotic/atlas-xcache-heartbeats:testing rucio --version
